# Project: network_programming_20171
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = server.o stdafx.o
LINKOBJ  = server.o stdafx.o
LIBS     = -L"E:/ProgramFiles/Dev-Cpp/MinGW64/lib" -L"E:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc ../../../../../ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libws2_32.a
INCS     = -I"E:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"E:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"E:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = network_programming_20171.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

server.o: server.cpp
	$(CPP) -c server.cpp -o server.o $(CXXFLAGS)

stdafx.o: stdafx.cpp
	$(CPP) -c stdafx.cpp -o stdafx.o $(CXXFLAGS)
